ISO_TIME_ZONES = {
    "north_america": [
        "America/Los_Angeles",
        "America/Denver",
        "America/Mexico_City",
        "America/Detroit",
        "America/Halifax",
        "America/St_Johns",
        "America/Phoenix",
    ],
    "south_america": [
        "America/Rio_Branco",
        "America/Manaus",
        "America/Cuiaba",
        "America/Bahia",
        "America/Sao_Paulo",
        "America/Noronha",
    ],
    "oceania": [
        "Australia/Adelaide",
        "Australia/Brisbane",
        "Australia/Darwin",
        "Australia/Perth",
        "Australia/Sydney",
        "Pacific/Auckland",
    ],
    "middle_east": ["Asia/Kolkata", "Asia/Riyadh", "Asia/Tehran"],
    "europe": [
        "Europe/London",
        "Europe/Paris",
        "Europe/Sofia",
        "Europe/Moscow",
        "Etc/UTC",
    ],
    "asia": ["Asia/Seoul", "Asia/Singapore", "Asia/Tokyo"],
}
